version: '3.8'

services:
  traefik:
    image: traefik:v3.3
    container_name: traefik-gateway
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - inventory_net

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inventory_net

  mongo-db:
    image: mongo:7.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - inventory_net

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - inventory_net

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db
      - redis-cache
    networks:
      - inventory_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/api/v1/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8081"

networks:
  inventory_net:
    driver: bridge
